version: "3.8"

services:
  api-solid-pg:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    networks:
      - app_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker-db 
    volumes:
      - "postgresql_data:/bitnami/postgresql" 

volumes:
  postgresql_data:

networks:
  app_network: